version: '{build}'
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
branches:
  only:
  - master
before_build:
- ps: nuget restore src\ExpressiveAnnotations.sln
build:
  project: src\ExpressiveAnnotations.sln
  parallel: true
  verbosity: minimal
test_script:
- ps: build\test.ps1
- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- codecov -f "csharp-coverage.xml"